@host = localhost
@port = 8080
@pathproject = academico-web-api

### Lista todos os endereços
GET http://{{host}}:{{port}}/{{pathproject}}/enderecos

### Busca um endereço específico por ID
GET http://{{host}}:{{port}}/{{pathproject}}/enderecos/13

### Criar um endereço
POST http://{{host}}:{{port}}/{{pathproject}}/enderecos
Content-type: application/json 

{
    "CEP": 490000,
    "bairro": "Centro",
    "cidade": "Itabaiana",
    "estado": "Sergipe",
    "rua": "Rua da Feira"
}

### Atualizar todos os atributos de um endereço
PUT http://{{host}}:{{port}}/{{pathproject}}/enderecos/100
content-type: application/json

{
    "CEP": 491000,
    "bairro": "Centro",
    "cidade": "Lagarto",
    "estado": "Sergipe",
    "rua": "Rua da Feira"
}

### Deletar um endereço
DELETE http://{{host}}:{{port}}/{{pathproject}}/enderecos/13

### Ativar/Desativar um endereço - Não CRUD
PUT http://{{host}}:{{port}}/{{pathproject}}/enderecos/100/status
Content-Type: text/plain

ATIVO